/**
 * scripts/conf/generated-paths.test.mjs
 *
 * Sibling of `templated-paths.test.mjs`, and deliberately a different concept.
 *
 * That file covers files AOI **shares** with the owner (`.vscode/*.json`): key
 * merged by setup.sh, skipped by the comparator, re-hashed here. AOI owns a few
 * keys in each and the owner owns the rest.
 *
 * This one covers files AOI **writes wholesale**, through `compile-rules.mjs`,
 * interpolating the workspace name. There is nothing to merge and nothing to
 * preserve: the file is AOI's, start to finish.
 *
 * Why they need their own list. `checksums.json` is generated by hashing the
 * SCAFFOLD, which is right for the ~360 files that arrive as a byte copy. For
 * these seven it recorded `workspace: AOI` — the product's own name — while the
 * installed file says `workspace: <project>`. The two can never agree, so every
 * reinstall read AOI's own output as an owner edit: the seven were kept stale
 * forever, AOI's future updates to them could never land, and any change to a
 * template surfaced as a CONFLICT asking the owner to merge a file they had
 * never opened. Observed on a real workspace before this list existed.
 *
 * The invariant is derivable, which is why it is asserted rather than
 * described: a file belongs on this list exactly when `compile-rules` writes it
 * AND its content carries the workspace name. Asserting the SET in both
 * directions means a new harness added to the compiler fails here instead of
 * quietly becoming an eighth stale file on someone's disk.
 */

import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, it } from 'node:test'
import { compileHarnessRules } from '../multi-harness/compile-rules.mjs'
import { shellList } from './templated-paths.test.mjs'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const SNAPSHOT = fs.readFileSync(path.join(REPO, 'scripts/conf/snapshot-conf.sh'), 'utf8')

/** A name no real workspace has, so a match cannot come from anywhere else. */
const PROBE = 'probe-workspace-9f3c'

/** The paths snapshot-conf.sh re-baselines from the installed tree. */
export const declaredGeneratedPaths = (script) => shellList(script, 'GENERATED_PATHS')

/**
 * Runs the real compiler over a throwaway tree and reports every file it wrote
 * that carries the workspace name.
 *
 * The compiler is run rather than its output table hardcoded: the point is to
 * measure what it does, not what it is documented to do.
 *
 * @returns {string[]} sorted repo-relative paths
 */
export function generatedWorkspaceFiles() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'aoi-generated-'))
  // The compiler reads the protocol to derive the store-trigger and MCP blocks,
  // so the probe gets the real one; without it those blocks fall back and the
  // generated text would not be what ships.
  fs.mkdirSync(path.join(tmp, '.github', 'instructions'), { recursive: true })
  fs.copyFileSync(
    path.join(REPO, '.github/instructions/icm-protocol.instructions.md'),
    path.join(tmp, '.github/instructions/icm-protocol.instructions.md')
  )

  compileHarnessRules(tmp, ['all'], PROBE)

  const found = []
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (fs.readFileSync(full, 'utf8').includes(PROBE)) found.push(path.relative(tmp, full))
    }
  }
  walk(tmp)

  fs.rmSync(tmp, { recursive: true, force: true })
  return found.sort()
}

describe('the generated-path list tracks what compile-rules actually writes', () => {
  it('declares exactly the files that carry the workspace name', () => {
    // Set equality in both directions on purpose. A missing entry is a file
    // that stays stale forever; a stale entry claims AOI owns a file it no
    // longer writes, and hides that the file stopped being generated.
    const actual = generatedWorkspaceFiles()
    assert.deepEqual(
      actual,
      declaredGeneratedPaths(SNAPSHOT),
      'la lista GENERATED_PATHS y lo que compile-rules escribe no coinciden.\n' +
        `  detectados: ${actual.join(', ')}\n` +
        `  declarados: ${declaredGeneratedPaths(SNAPSHOT).join(', ')}\n` +
        'Un archivo generado que no esté declarado queda desactualizado para siempre: ' +
        'su baseline es el del scaffold (workspace: AOI) y nunca puede coincidir.'
    )
  })

  it('finds the seven known dialects, so the detector is not vacuous', () => {
    // Without this, a compile-rules that stopped writing anything would make
    // the equality above pass against an empty list.
    const actual = generatedWorkspaceFiles()
    assert.ok(
      actual.length >= 7,
      `el detector encontró ${actual.length} archivo(s); se esperaban al menos 7`
    )
    for (const rel of ['.github/copilot-instructions.md', 'CLAUDE.md', 'AGENTS.md']) {
      assert.ok(actual.includes(rel), `no detectó ${rel}: ${actual.join(', ')}`)
    }
  })

  it('every generated file carries the marker the guard checks', () => {
    // snapshot-conf.sh only re-baselines a generated file whose content carries
    // GENERATED_MARKER. If a dialect ever changed its header, the guard would
    // reject it and the fix would silently stop applying to that file.
    const m = SNAPSHOT.match(/GENERATED_MARKER="([^"]*)"/)
    assert.ok(m, 'snapshot-conf.sh ya no declara GENERATED_MARKER')
    const marker = m[1]

    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'aoi-marker-'))
    fs.mkdirSync(path.join(tmp, '.github', 'instructions'), { recursive: true })
    fs.copyFileSync(
      path.join(REPO, '.github/instructions/icm-protocol.instructions.md'),
      path.join(tmp, '.github/instructions/icm-protocol.instructions.md')
    )
    compileHarnessRules(tmp, ['all'], PROBE)

    for (const rel of declaredGeneratedPaths(SNAPSHOT)) {
      const full = path.join(tmp, rel)
      assert.ok(fs.existsSync(full), `compile-rules no escribió ${rel}`)
      assert.ok(
        fs.readFileSync(full, 'utf8').includes(marker),
        `${rel} no lleva el marcador "${marker}", así que la guarda no lo re-basearía`
      )
    }
    fs.rmSync(tmp, { recursive: true, force: true })
  })

  it('does not overlap the key-merged list, which is a different contract', () => {
    // A path in both lists would be re-baselined by two different rules. Today
    // they cannot overlap — one set is JSON AOI shares, the other is Markdown
    // AOI writes whole — and this keeps it that way.
    const shared = declaredGeneratedPaths(SNAPSHOT).filter((rel) =>
      shellList(SNAPSHOT, 'TEMPLATED_PATHS').includes(rel)
    )
    assert.deepEqual(shared, [], `declarado en las dos listas: ${shared.join(', ')}`)
  })
})
