/**
 * server/utils/c4-generator.ts
 *
 * Dynamic C4 Architecture Generator for AOI-OS Nitro API.
 */

export interface DagNodeLike {
  id: string
  title: string
  role: string
  dependsOn?: string[]
  targetFiles?: string[]
  status?: string
}

export function generateC4ArchitectureDiagram(
  dagNodes: DagNodeLike[] = [],
  options: { systemName?: string } = {}
) {
  const { systemName = 'AOI-OS Governed System' } = options

  if (!dagNodes.length) {
    return {
      mermaidDiagram: 'graph TD\n  Empty["No components discovered"]',
      containerCount: 0,
      relationsCount: 0,
    }
  }

  const lines = [
    '%% Live C4 Dynamic Component Architecture Generated by AOI-OS',
    'graph TB',
    `  subgraph System["${systemName}"]`,
  ]

  let relationsCount = 0

  for (const node of dagNodes) {
    const safeTitle = node.title.replace(/"/g, "'")
    const roleTag = `@${node.role}`
    const fileTag = node.targetFiles?.[0] ? `\\n[${node.targetFiles[0]}]` : ''
    const statusIcon = node.status === 'completed' ? '✅ ' : node.status === 'in_progress' ? '⚡ ' : ''

    lines.push(`    ${node.id}["${statusIcon}${node.id}: ${safeTitle}\\n(${roleTag})${fileTag}"]`)
  }

  lines.push('  end')

  // Generate relationship edges
  for (const node of dagNodes) {
    if (node.dependsOn && node.dependsOn.length) {
      for (const dep of node.dependsOn) {
        lines.push(`  ${dep} -->|depends on| ${node.id}`)
        relationsCount++
      }
    }
  }

  return {
    mermaidDiagram: lines.join('\n'),
    containerCount: dagNodes.length,
    relationsCount,
  }
}
